export { default as Home } from "./Home";
export { default as Auth } from "./Auth";
export { default as PageNotFound } from "./PageNotFound";
export { default as Feedbacks } from "./Feedbacks";
export { default as Templates } from "./Templates";
export { default as Staff } from "./Staff";
export { default as Dashboard } from "./Dashboard";
export { default as Setting } from "./Setting";
export { default as CreateFeedback } from "./CreateFeedback";
